# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 13:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('descr', models.TextField()),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857)),
                ('tile_url', models.TextField(default='https://a.tile.openstreetmap.org/0/0/0.png')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Noname')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_objects', to='app.Dataset')),
                ('geom_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_objects', to='app.GeomType')),
            ],
        ),
        migrations.CreateModel(
            name='NumValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.DateTimeField(blank=True, null=True)),
                ('interval', models.DurationField(blank=True, null=True)),
                ('num_vals', models.IntegerField(default=1)),
                ('name', models.TextField(default='Noname')),
                ('model_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app.ModelObject')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RasterSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.gis.db.models.fields.RasterField(srid=3857)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raster_series', to='app.Prop')),
            ],
        ),
        migrations.CreateModel(
            name='RasValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.gis.db.models.fields.RasterField(null=True, srid=3857)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ras_values', to='app.Prop')),
            ],
        ),
        migrations.CreateModel(
            name='ValueSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_series', to='app.Prop')),
            ],
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='prop',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app.PropertyType'),
        ),
        migrations.AddField(
            model_name='prop',
            name='value_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app.ValueType'),
        ),
        migrations.AddField(
            model_name='numvalue',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_values', to='app.Prop'),
        ),
        migrations.AddField(
            model_name='modelobject',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_objects', to='app.ObjectType'),
        ),
        migrations.AddField(
            model_name='catvalue',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_values', to='app.Prop'),
        ),
    ]
