# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 11:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170125_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prop',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='prop',
            name='num_vals',
        ),
        migrations.RemoveField(
            model_name='prop',
            name='timestart',
        ),
        migrations.AddField(
            model_name='prop',
            name='sampled_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='app.ModelObject'),
        ),
        migrations.AddField(
            model_name='rasterseries',
            name='timestamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='valueseries',
            name='timestamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(null=True), null=True, size=None),
        ),
    ]
