# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170209_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelobject',
            name='name',
            field=models.CharField(default='Noname', max_length=80),
        ),
    ]
