# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170209_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='descr',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelobject',
            name='name',
            field=models.CharField(default='Noname', max_length=100),
        ),
        migrations.AlterField(
            model_name='prop',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
